In [ ]:
What is a Random Number?
Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

Pseudo Random and True Random.
Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm 
to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data
from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless its related to security (e.g. encryption keys) or the basis of application 
is the randomness (e.g. Digital roulette wheels).

In this tutorial we will be using pseudo random numbers.

In [ ]:
Generate Random Number
NumPy offers the random module to work with random numbers.

In [7]:
from numpy import random

x = random.randint(100)

print(x)

25


In [3]:
Generate Random Float
The random module's rand() method returns a random float between 0 and 1.

SyntaxError: invalid syntax (2881275503.py, line 1)

In [10]:
from numpy import random

x = random.rand()

print(x)

0.7245796178510088


In [9]:
Generate Random Array
In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

Integers
The randint() method takes a size parameter where you can specify the shape of an array.

SyntaxError: invalid syntax (1681894808.py, line 1)

In [16]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[81 75 82 22 90]


In [17]:
from numpy import random

x = random.randint(100, size=(5, 5))

print(x)

[[ 1  0 79 16 49]
 [37 70 77 76 58]
 [73 24 25 76 79]
 [17 47 78  0 38]
 [70 94 34  4 86]]


In [ ]:
The rand() method also allows you to specify the shape of the array.

In [18]:
from numpy import random

x = random.rand(6)

print(x)

[0.63206208 0.23492614 0.11228898 0.98412149 0.9799555  0.51176477]


In [7]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.1792635  0.29862872 0.22480005 0.57791907 0.69238087]
 [0.32813258 0.43413975 0.68426043 0.72313195 0.67836027]
 [0.23631958 0.48024329 0.72241319 0.89634358 0.3840771 ]]


In [ ]:
Generate Random Number From Array
The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

In [12]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

9


In [ ]:
The choice() method also allows you to return an array of values.

Add a size parameter to specify the shape of the array.

In [14]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)


[[7 5 3 5 3]
 [3 7 5 5 3]
 [9 3 9 9 5]]


In [ ]:
What is Data Distribution?
Data Distribution is a list of all possible values, and how often each value occurs.

Such lists are important when working with statistics and data science.

The random module offer methods that returns randomly generated data distributions.

Random Distribution
A random distribution is a set of random numbers that follow a certain probability density function.

Probability Density Function: A function that describes a continuous probability. i.e. probability of all values in an array.

We can generate random numbers based on defined probabilities using the choice() method of the random module.

The choice() method allows us to specify the probability for each value.

The probability is set by a number between 0 and 1, where 0 means that the value will never occur and 1 means that the value will always occur.

ExampleGet your own Python Server
Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

The probability for the value to be 3 is set to be 0.1

The probability for the value to be 5 is set to be 0.3

The probability for the value to be 7 is set to be 0.6

The probability for the value to be 9 is set to be 0


The sum of all probability numbers should be 1.

Even if you run the example above 100 times, the value 9 will never occur.

You can return arrays of any shape and size by specifying the shape in the size parameter.



In [10]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 5 7 7 3 7 5 5 7 7 7 3 7 7 5 5 7 5 7 5 7 7 5 5 5 5 5 7 7 7 3 5 3 7 7 7 7
 3 5 7 7 5 5 7 5 7 7 5 7 7 5 5 5 7 7 7 5 7 7 7 7 3 7 5 3 7 7 7 3 5 7 7 5 7
 3 7 5 7 5 7 7 3 7 7 7 5 7 7 7 5 7 7 7 7 7 3 5 5 7 7]


In [11]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[7 7 7 5 7]
 [7 7 7 7 5]
 [7 7 7 7 5]]


In [ ]:
Random Permutations of Elements
A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

The NumPy Random module provides two methods for this: shuffle() and permutation().

Shuffling Arrays
Shuffle means changing arrangement of elements in-place. i.e. in the array itself.

In [12]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[1 2 3 5 4]


In [13]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[3 4 2 5 1]


In [ ]:
Normal Distribution
The Normal Distribution is one of the most important distributions.

It is also called the Gaussian Distribution after the German mathematician Carl Friedrich Gauss.

It fits the probability distribution of many events, eg. IQ Scores, Heartbeat etc.

Use the random.normal() method to get a Normal Data Distribution.

It has three parameters:

loc - (Mean) where the peak of the bell exists.

scale - (Standard Deviation) how flat the graph distribution should be.

size - The shape of the returned array.

In [14]:
from numpy import random

x = random.normal(size=(2, 3))

print(x)

[[-0.39906496  0.19906327 -1.63505139]
 [-0.11250515 -0.7648945   0.87737243]]


In [15]:
from numpy import random

x = random.normal(loc=1, scale=2, size=(2, 3))

print(x)

[[0.8960597  3.19775814 1.19083356]
 [2.16350868 2.93449865 0.14949849]]


In [ ]:
Binomial Distribution
Binomial Distribution is a Discrete Distribution.

It describes the outcome of binary scenarios, e.g. toss of a coin, it will either be head or tails.

It has three parameters:

n - number of trials.

p - probability of occurence of each trial (e.g. for toss of a coin 0.5 each).

size - The shape of the returned array.

Discrete Distribution:The distribution is defined at separate set of events, e.g. a coin toss's
    result is discrete as it can be only head or tails whereas height of people is continuous as it 
    can be 170, 170.1, 170.11 and so on.

In [16]:
from numpy import random

x = random.binomial(n=10, p=0.5, size=10)

print(x)

[6 3 7 6 7 5 7 5 6 8]


In [ ]:
Poisson Distribution
Poisson Distribution is a Discrete Distribution.

It estimates how many times an event can happen in a specified time. e.g. If someone eats twice a day what 
is the probability he will eat thrice?

It has two parameters:

lam - rate or known number of occurrences e.g. 2 for above problem.

size - The shape of the returned array.

In [17]:
from numpy import random

x = random.poisson(lam=2, size=10)

print(x)

[4 4 1 2 1 2 3 1 2 2]


In [ ]:
Uniform Distribution
Used to describe probability where every event has equal chances of occuring.

E.g. Generation of random numbers.

It has three parameters:

a - lower bound - default 0 .0.

b - upper bound - default 1.0.

size - The shape of the returned array.

In [19]:
from numpy import random

x = random.uniform(size=(2, 3))

print(x)

[[0.26737311 0.44346206 0.87425133]
 [0.86231235 0.80197611 0.66252505]]


In [18]:
Logistic Distribution
Logistic Distribution is used to describe growth.

Used extensively in machine learning in logistic regression, neural networks etc.

It has three parameters:

loc - mean, where the peak is. Default 0.

scale - standard deviation, the flatness of distribution. Default 1.

size - The shape of the returned array.

SyntaxError: invalid syntax (3233759024.py, line 1)

In [21]:
from numpy import random

x = random.logistic(loc=1, scale=2, size=(2, 3))

print(x)

[[ 4.04609643 -0.69160271  3.85953864]
 [ 4.10670547  0.27056005 -4.50894611]]


In [20]:
Multinomial Distribution
Multinomial distribution is a generalization of binomial distribution.

It describes outcomes of multi-nomial scenarios unlike binomial where scenarios must be only one of two.
e.g. Blood type of a population, dice roll outcome.

It has three parameters:

n - number of possible outcomes (e.g. 6 for dice roll).

pvals - list of probabilties of outcomes (e.g. [1/6, 1/6, 1/6, 1/6, 1/6, 1/6] for dice roll).

size - The shape of the returned array.

SyntaxError: invalid syntax (2058189646.py, line 1)

In [22]:
from numpy import random

x = random.multinomial(n=6, pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6])

print(x)

[1 1 4 0 0 0]


In [ ]:
Exponential Distribution
Exponential distribution is used for describing time till next event e.g. failure/success etc.

It has two parameters:

scale - inverse of rate ( see lam in poisson distribution ) defaults to 1.0.

size - The shape of the returned array.

In [23]:
from numpy import random

x = random.exponential(scale=2, size=(2, 3))

print(x)

[[0.29468622 0.98140998 1.0104162 ]
 [1.08542285 4.70033387 1.39950327]]


In [ ]:
Chi Square Distribution
Chi Square distribution is used as a basis to verify the hypothesis.

It has two parameters:

df - (degree of freedom).

size - The shape of the returned array.

In [26]:
from numpy import random

x = random.chisquare(df=2, size=(2, 3))

print(x)

[[2.73443109 0.5151884  5.10549951]
 [0.37260964 0.42168575 0.64935516]]


In [ ]:
Rayleigh Distribution
Rayleigh distribution is used in signal processing.

It has two parameters:

scale - (standard deviation) decides how flat the distribution will be default 1.0).

size - The shape of the returned array.

In [27]:
from numpy import random

x = random.rayleigh(scale=2, size=(2, 3))

print(x)


[[3.5490092  1.72432731 1.34346671]
 [3.50914156 3.37379503 4.18033336]]


In [ ]:
Pareto Distribution
A distribution following Pareto's law i.e. 80-20 distribution (20% factors cause 80% outcome).

It has two parameter:

a - shape parameter.

size - The shape of the returned array.

In [ ]:
from numpy import random

x = random.pareto(a=2, size=(2, 3))

print(x)

In [ ]:
Zipf distritutions are used to sample data based on zipf's law.

Zipf's Law: In a collection, the nth common term is 1/n times of the most common term. E.g. the 5th most 
common word in English occurs nearly 1/5 times as often as the most common word.

It has two parameters:

a - distribution parameter.

size - The shape of the returned array.

In [28]:
from numpy import random

  x = random.zipf(a=2, size=(2, 3))

print(x)

[[2 2 1]
 [1 2 1]]
